version: '3.8'

networks:
  default: 

services:
  client:
    depends_on:
      - server
    build:
      context: ./client
    container_name: nextjs-client
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
     - "3000:3000"
    restart: always
    networks:
      - default
  server:
    depends_on:
      - db
    build:
      context: ./server
    container_name: node-server
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
     - "3001:3001"
    restart: always
    env_file:
      - ./server/.env
    # command:
    #   dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region ap-northeast-1
    networks:
      - default
  db:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "6666:6666"
    restart: always
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 6666"
    volumes:
      - ./db/data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - default
  db-admin:
    build: 
      context: ./db-admin
    container_name: dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: 'http://db:6666'
      # PORT: 8001 # default port for dynamodb-admin
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'ap-northeast-1'
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - db
    volumes:
      - ./db-admin/node_modules:/app/node_modules
    networks:
      - default


