version: '3.8'

networks:
  default: 

services:
  client:
    depends_on:
      - server
    build:
      context: ./client
    container_name: nextjs-client
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
     - "${CLIENT_HOST_PORT}:3000"
    restart: always
    env_file:
      - .env
      - ./client/.env.local
    networks:
      - default
  server:
    depends_on:
      - db
    build:
      context: ./server
    container_name: node-server
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
     - "${SERVER_HOST_PORT}:3001"
    restart: always
    env_file:
      - .env
      - ./server/.env.local
    networks:
      - default
  db:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "${DB_HOST_PORT}:8000"
    restart: always
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port ${DB_HOST_PORT}"
    volumes:
      - ./db/data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - default
  db-admin:
    build: 
      context: ./db-admin
    container_name: dynamodb-admin
    env_file:
      - .env
    environment:
      DYNAMO_ENDPOINT: 'http://${DB_HOST}:${DB_HOST_PORT}'
      # PORT: 8001 # default port for dynamodb-admin
    ports:
      - "${DB_ADMIN_HOST_PORT}:8001"
    restart: always
    depends_on:
      - db
    volumes:
      - ./db-admin/node_modules:/app/node_modules
    networks:
      - default
